name: Publish Docker image

on:
  push:
    branches:
      - 'main'
    paths:
      - 'negative_prompts/**'
      - 'Dockerfile'
      - '.zshrc'
      - 'extra_downloads.yml'
      - 'extra_model_paths.yml'
      - 'magic'
  pull_request:
    branches:
      - 'main'
    paths:
      - 'negative_prompts/**'
      - 'Dockerfile'
      - '.zshrc'
      - 'extra_downloads.yml'
      - 'extra_model_paths.yml'
      - 'magic'
  schedule:
    # re-run monthly to keep image fresh
    - cron: '0 12 15 * *'

  workflow_dispatch:
  
jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repo
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      if: github.event_name != 'pull_request '
      uses: docker/login-action@v3.0.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Extract metadata
      id: docker_meta
      uses: docker/metadata-action@v5.4.0
      with:
        images: name/app
        flavor: |
          latest=false
        tags: |
          type=semver,pattern={{version}}

    - name: Build and push Docker image
      id: docker_build
      uses: docker/build-push-action@v5.1.0
      with:
        platforms: linux/amd64,linux/arm64
        context: .
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.docker_meta.outputs.tags }}
        labels: ${{ steps.docker_meta.outputs.labels }}
    
    - name: Show image digest
      run: echo ${{ steps.docker_build.outputs.digest }}